<a href="https://colab.research.google.com/github/victoricoma/am-turma5/blob/main/ConsumoAPI_aula0915.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pipeline de Analise de Dados [API - Churn]

## Importação de Bibliotecas

*   Pandas
*   Numpy
*   MatPlotLib
*   SeaBorn

In [1]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.13/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import requests

API_KEY = '1RY5Q4P9BZDSKR9L'
EMPRESA = 'NFLX'

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={EMPRESA}&apikey={API_KEY}'
response = requests.get(url)
dia_netflix = response.json()
base_dia_netflix = pd.DataFrame(dia_netflix['Time Series (Daily)']).T
base_dia_netflix

            1. open  2. high   3. low 4. close 5. volume
2026-09-14  78.9700  81.0200  78.4900  80.3200  30945111
2026-09-11  76.6400  77.5661  76.1500  77.4000  22237769
2026-09-10  75.3250  76.3000  75.0300  76.0100  20049027
2026-09-09  76.3400  76.7200  75.8700  76.0300  22779615
2026-09-08  77.5500  77.7300  75.9200  76.7700  33865470
...             ...      ...      ...      ...       ...
2026-04-28  91.5000  92.3400  90.0200  92.2700  33418126
2026-04-27  92.0500  92.8400  91.3000  91.3700  29707439
2026-04-24  92.5700  93.2800  91.8000  92.4400  32553177
2026-04-23  94.0600  94.6400  92.0730  92.8200  36851674
2026-04-22  93.0600  93.8500  92.7700  93.2400  33694345

[100 rows x 5 columns]

In [10]:
EMPRESA = 'NVDA'

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={EMPRESA}&apikey={API_KEY}'
response = requests.get(url)
dia_netflix = response.json()
base_dia_netflix = pd.DataFrame(dia_netflix['Time Series (Daily)']).T
base_dia_netflix

             1. open   2. high    3. low  4. close  5. volume
2026-09-14  211.2400  212.7700  208.9300  210.9600  132267244
2026-09-11  221.2350  222.0000  218.1500  218.2900   89060140
2026-09-10  220.5250  220.9900  217.2000  218.3600  105768001
2026-09-09  225.2750  226.1800  223.4600  223.6700   82955478
2026-09-08  233.1100  233.7100  224.8500  225.7300  122965555
...              ...       ...       ...       ...        ...
2026-04-28  209.4900  214.7300  208.2000  213.1700  180275363
2026-04-27  209.6450  216.8250  207.3800  216.6100  187172421
2026-04-24  199.9600  210.9500  199.8100  208.2700  214134441
2026-04-23  202.4600  203.8290  197.2206  199.6400  113561830
2026-04-22  200.9900  202.5000  199.0000  202.5000  107501042

[100 rows x 5 columns]

In [15]:
url = f'https://valorant-api.com/v1/agents'
response = requests.get(url)
lista_agentes = response.json()
lista_agentes
base_agentes = pd.DataFrame(lista_agentes['data'])
base_agentes

,uuid,displayName,description,developerName,releaseDate,characterTags,displayIcon,displayIconSmall,bustPortrait,fullPortrait,...,backgroundGradientColors,assetPath,isFullPortraitRightFacing,isPlayableCharacter,isAvailableForTest,isBaseContent,role,recruitmentData,abilities,voiceLine
0,e370fa57-4757-3604-3648-499e1f642d3f,Gekko,Gekko the Angeleno leads a tight-knit crew of ...,Aggrobot,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/e370fa57...,https://media.valorant-api.com/agents/e370fa57...,https://media.valorant-api.com/agents/e370fa57...,https://media.valorant-api.com/agents/e370fa57...,...,"[371c5cff, 0f1923ff, 3a2656ff, 0f192300]",ShooterGame/Content/Characters/AggroBot/AggroB...,False,True,False,False,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Ability1', 'displayName': 'Wingman'...",None
1,dade69b4-4f5a-8528-247b-219e5a1facd6,Fade,Turkish bounty hunter Fade unleashes the power...,BountyHunter,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/dade69b4...,https://media.valorant-api.com/agents/dade69b4...,https://media.valorant-api.com/agents/dade69b4...,https://media.valorant-api.com/agents/dade69b4...,...,"[1d2846ff, 0f1923ff, 18344cff, 0f192300]",ShooterGame/Content/Characters/BountyHunter/Bo...,False,True,True,False,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Ability1', 'displayName': 'Seize', ...",None
2,5f8d3a7f-467b-97f3-062c-13acf203c006,Breach,"The bionic Swede Breach fires powerful, target...",Breach,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/5f8d3a7f...,https://media.valorant-api.com/agents/5f8d3a7f...,https://media.valorant-api.com/agents/5f8d3a7f...,https://media.valorant-api.com/agents/5f8d3a7f...,...,"[81331aff, 0f1923ff, 523a23ff, 0f192300]",ShooterGame/Content/Characters/Breach/Breach_P...,False,True,True,False,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Ability1', 'displayName': 'Flashpoi...",None
3,cc8b64c8-4b25-4ff9-6e7f-37b4da43d235,Deadlock,Norwegian operative Deadlock deploys an array ...,Cable,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/cc8b64c8...,https://media.valorant-api.com/agents/cc8b64c8...,https://media.valorant-api.com/agents/cc8b64c8...,https://media.valorant-api.com/agents/cc8b64c8...,...,"[425495ff, 0f1923ff, 221c3dff, 0f192300]",ShooterGame/Content/Characters/Cable/Cable_Pri...,False,True,False,False,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,{'counterId': '7ec37a1e-4526-77dd-1afd-e2ab3b6...,"[{'slot': 'Ability1', 'displayName': 'Sonic Se...",None
4,b444168c-4e35-8076-db47-ef9bf368f384,Tejo,A veteran intelligence consultant from Colombi...,Cashew,2025-01-08T22:00:00Z,None,https://media.valorant-api.com/agents/b444168c...,https://media.valorant-api.com/agents/b444168c...,https://media.valorant-api.com/agents/b444168c...,https://media.valorant-api.com/agents/b444168c...,...,"[80451bff, 0f1923ff, ffffffff, 0f192300]",ShooterGame/Content/Characters/Cashew/Cashew_P...,False,True,False,False,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,{'counterId': 'b444168c-4e35-8076-db47-ef9bf36...,"[{'slot': 'Ability2', 'displayName': 'Guided S...",None
5,f94c3b30-42be-e959-889c-5aa313dba261,Raze,Raze explodes out of Brazil with her big perso...,Clay,1970-01-01T00:00:00Z,[Area Damage Specialist],https://media.valorant-api.com/agents/f94c3b30...,https://media.valorant-api.com/agents/f94c3b30...,https://media.valorant-api.com/agents/f94c3b30...,https://media.valorant-api.com/agents/f94c3b30...,...,"[742e1eff, 0f1923ff, 2c5942ff, 0f192300]",ShooterGame/Content/Characters/Clay/Clay_Prima...,False,True,True,False,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,None,"[{'slot': 'Ability1', 'displayName': 'Blast Pa...",None
6,22697a3d-45bf-8dd7-4fec-84a9e28c69d7,Chamber,"Well-dressed and well-armed, French weapons de...",Deadeye,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/22697a3d...,https://media.valorant-api.com/agents/22697a3d...,https://media.valorant-api.com/agents/22697a3d...,https://media.valorant-api.com/agents/22697a3d...,...,"[20435bff, 0f1923ff, 372d2bff, 0f192300]",ShooterGame/Content/Characters/Deadeye/Deadeye...,False,True,True,False,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,None,"[{'slot': 'Ability2', 'displayName': 'Rendezvo...",None
7,601dbbe7-43ce-be57-2a40-4abd24953621,KAY/O,KAY/O is a machine of war built for a single p...,Grenadier,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/601dbbe7...,https://media.valorant-api.com/agents/601dbbe7...,https://media.valorant-api.com/agents/601dbbe7...,https://media.valorant-api.com/agents/601dbbe7...,...,"[1c2a69ff, 0f1923ff, 1a1e4bff, 0f192300]",ShooterGame/Content/Characters/Grenadier/Grena...,False,True,True,False,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Grenade', 'displayName': 'FRAG/ment...",None
8,6f2a04ca-43e0-be17-7f36-b3908627744d,Skye,"Hailing from Australia, Skye and her band of b...",Guide,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/6f2a04ca...,https://media.valorant-api.com/agents/6f2a04ca...,https://media.valorant-api.com/agents/6f2a04ca...,https://media.valorant-api.com/agents/6f2a04ca...,...,"[436a51ff, 0f1923ff, 4f1413ff, 0f192300]",ShooterGame/Content/Characters/Guide/Guide_Pri...,False,True,True,False,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Ability1', 'displayName': 'Trailbla...",None
9,117ed9e3-49f3-6512-3ccf-0cada7e3823b,Cypher,"The Moroccan information broker, Cypher is a o...",Gumshoe,1970-01-01T00:00:00Z,"[Detection, Defensive Lockdown]",https://media.valorant-api.com/agents/117ed9e3...,https://media.valorant-api.com/agents/117ed9e3...,https://media.valorant-api.com/agents/117ed9e3...,https://media.valorant-api.com/agents/117ed9e3...,...,"[2f5078ff, 0f1923ff, 3f3f6cff, 0f192300]",ShooterGame/Content/Characters/Gumshoe/Gumshoe...,True,True,True,False,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,None,"[{'slot': 'Ability1', 'displayName': 'Cyber Ca...",None
10,320b2a48-4d9b-a075-30f1-1f93a9b638fa,Sova,Born from the eternal winter of Russia's tundr...,Hunter,1970-01-01T00:00:00Z,"[Detection, Area Damage]",https://media.valorant-api.com/agents/320b2a48...,https://media.valorant-api.com/agents/320b2a48...,https://media.valorant-api.com/agents/320b2a48...,https://media.valorant-api.com/agents/320b2a48...,...,"[355285ff, 0f1923ff, 101c47ff, 0f192300]",ShooterGame/Content/Characters/Hunter/Hunter_P...,False,True,True,True,{'uuid': '1b47567f-8f7b-444b-aae3-b0c634622d10...,None,"[{'slot': 'Ability1', 'displayName': 'Shock Bo...",None
11,7c8a4701-4de6-9355-b254-e09bc2a34b72,Miks,"Straight from Croatia, Miks takes the stage ch...",Iris,2026-03-18T15:00:00Z,None,https://media.valorant-api.com/agents/7c8a4701...,https://media.valorant-api.com/agents/7c8a4701...,https://media.valorant-api.com/agents/7c8a4701...,https://media.valorant-api.com/agents/7c8a4701...,...,"[462b75ff, 0f1923ff, 344673ff, 0f192300]",ShooterGame/Content/Characters/Iris/Iris_Prima...,False,True,True,False,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,{'counterId': '7c8a4701-4de6-9355-b254-e09bc2a...,"[{'slot': 'Grenade', 'displayName': 'M-pulse',...",None
12,1e58de9c-4950-5125-93e9-a0aee9f98746,Killjoy,"The genius of Germany, Killjoy effortlessly se...",Killjoy,1970-01-01T00:00:00Z,"[Defensive Lockdown, Area Damage]",https://media.valorant-api.com/agents/1e58de9c...,https://media.valorant-api.com/agents/1e58de9c...,https://media.valorant-api.com/agents/1e58de9c...,https://media.valorant-api.com/agents/1e58de9c...,...,"[522162ff, 0f1923ff, 413950ff, 0f192300]",ShooterGame/Content/Characters/Killjoy/Killjoy...,False,True,True,False,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,None,"[{'slot': 'Grenade', 'displayName': 'Nanoswarm...",None
13,95b78ed7-4637-86d9-7e41-71ba8c293152,Harbor,"Hailing from India’s coast, Harbor storms the ...",Mage,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/95b78ed7...,https://media.valorant-api.com/agents/95b78ed7...,https://media.valorant-api.com/agents/95b78ed7...,https://media.valorant-api.com/agents/95b78ed7...,...,"[275146ff, 0f1923ff, 11434eff, 0f192300]",ShooterGame/Content/Characters/Mage/Mage_Prima...,False,True,True,False,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,None,"[{'slot': 'Ability1', 'displayName': 'High Tid...",None
14,efba5359-4016-a1e5-7626-b1ae76895940,Vyse,Metallic mastermind Vyse unleashes liquid meta...,Nox,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/efba5359...,https://media.valorant-api.com/agents/efba5359...,https://media.valorant-api.com/agents/efba5359...,https://media.valorant-api.com/agents/efba5359...,...,"[492280ff, 0f1923ff, ffffffff, 0f192300]",ShooterGame/Content/Characters/Nox/Nox_Primary...,False,True,True,False,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,{'counterId': '5cf4f9ee-4ace-08c3-ea08-9b98dad...,"[{'slot': 'Ability1', 'displayName': 'Shear', ...",None
15,707eab51-4836-f488-046a-cda6bf494859,Viper,"The American Chemist, Viper deploys an array o...",Pandemic,1970-01-01T00:00:00Z,[Vision Control Specialist],https://media.valorant-api.com/agents/707eab51...,https://media.valorant-api.com/agents/707eab51...,https://media.valorant-api.com/agents/707eab51...,https://media.valorant-api.com/agents/707eab51...,...,"[1a5f46ff, 0f1923ff, 2c4f5eff, 0f192300]",ShooterGame/Content/Characters/Pandemic/Pandem...,False,True,True,False,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,None,"[{'slot': 'Ability1', 'displayName': 'Poison C...",None
16,eb93336a-449b-9c1b-0a54-a891f7921d69,Phoenix,"Hailing from the U.K., Phoenix's star power sh...",Phoenix,1970-01-01T00:00:00Z,"[Flexibility, Self-Sustain]",https://media.valorant-api.com/agents/eb93336a...,https://media.valorant-api.com/agents/eb93336a...,https://media.valorant-api.com/agents/eb93336a...,https://media.valorant-api.com/agents/eb93336a...,...,"[74321cff, 0f1923ff, 262423ff, 0f192300]",ShooterGame/Content/Characters/Phoenix/Phoenix...,True,True,True,True,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,None,"[{'slot': 'Grenade', 'displayName': 'Blaze', '...",None
17,92eeef5d-43b5-1d4a-8d03-b3927a09034b,Veto,"Empowered by an unstoppable DNA mutation, Sene...",Pine,2025-10-07T22:00:00Z,None,https://media.valorant-api.com/agents/92eeef5d...,https://media.valorant-api.com/agents/92eeef5d...,https://media.valorant-api.com/agents/92eeef5d...,https://media.valorant-api.com/agents/92eeef5d...,...,"[1a5d65ff, 0f1923ff, 0f1923ff, 1a5d65ff]",ShooterGame/Content/Characters/Pine/Pine_Prima...,False,True,False,False,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,{'counterId': '92eeef5d-43b5-1d4a-8d03-b3927a0...,"[{'slot': 'Ability2', 'displayName': 'Intercep...",None
18,41fb69c1-4189-7b37-f117-bcaf1e96f1bf,Astra,Ghanaian Agent Astra harnesses the energies of...,Rift,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/41fb69c1...,https://media.valorant-api.com/agents/41fb69c1...,https://media.valorant-api.com/agents/41fb69c1...,https://media.valorant-api.com/agents/41fb69c1...,...,"[26146cff, 0f1923ff, 5210c6ff, 0f192300]",ShooterGame/Content/Characters/Rift/Rift_Prima...,True,True,True,False,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,None,"[{'slot': 'Ability1', 'displayName': 'Nova Pul...",None
19,9f0d8ba9-4140-b941-57d3-a7ad57c6b417,Brimstone,"Joining from the U.S.A., Brimstone's orbital a...",Sarge,1970-01-01T00:00:00Z,"[Vision Control, Area Damage]",https://media.valorant-api.com/agents/9f0d8ba9...,https://media.valorant-api.com/agents/9f0d8ba9...,https://media.valorant-api.com/agents/9f0d8ba9...,https://media.valorant-api.com/agents/9f0d8ba9...,...,"[363c4fff, 0f1923ff, 211d21ff, 0f192300]",ShooterGame/Content/Characters/Sarge/Sarge_Pri...,False,True,True,True,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,None,"[{'slot': 'Grenade', 'displayName': 'Stim Beac...",None
20,0e38b510-41a8-5780-5e8f-568b2a4f2d6c,Iso,Chinese fixer for hire Iso falls into a flow s...,Sequoia,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/0e38b510...,https://media.valorant-api.com/agents/0e38b510...,https://media.valorant-api.com/agents/0e38b510...,https://media.valorant-api.com/agents/0e38b510...,...,"[30336eff, 0f1923ff, 20155dff, 0f192300]",ShooterGame/Content/Characters/Sequoia/Sequoia...,False,True,False,False,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,{'counterId': '23012172-4c2f-13cf-f70c-d584a80...,"[{'slot': 'Ability1', 'displayName': 'Undercut...",None
21,1dbf2edd-4729-0984-3115-daa5eed44993,Clove,Scottish troublemaker Clove makes mischief for...,Smonk,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/1dbf2edd...,https://media.valorant-api.com/agents/1dbf2edd...,https://media.valorant-api.com/agents/1dbf2edd...,https://media.valorant-api.com/agents/1dbf2edd...,...,"[4b1d80ff, 0f1923ff, c347c7ff, 0f192300]",ShooterGame/Content/Characters/Smonk/Smonk_Pri...,False,True,True,False,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,{'counterId': '1064ba88-4cd9-8d5b-cbe5-d784b35...,"[{'slot': 'Grenade', 'displayName': 'Pick-me-u...",None
22,bb2a4828-46eb-8cd1-e765-15848195d751,Neon,Filipino Agent Neon surges forward at shocking...,Sprinter,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/bb2a4828...,https://media.valorant-api.com/agents/bb2a4828...,https://media.valorant-api.com/agents/bb2a4828...,https://media.valorant-api.com/agents/bb2a4828...,...,"[413476ff, 0f1923ff, 38328eff, 0f192300]",ShooterGame/Content/Characters/Sprinter/Sprint...,False,True,True,False,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,None,"[{'slot': 'Ability2', 'displayName': 'High Gea...",None
23,7f94d92c-4234-0a36-9646-3a87eb8b5c89,Yoru,Japanese native Yoru rips holes straight throu...,Stealth,1970-01-01T00:00:00Z,None,https://media.valorant-api.com/agents/7f94d92c...,https://media.valorant-api.com/agents/7f94d92c...,https://media.valorant-api.com/agents/7f94d92c...,https://media.valorant-api.com/agents/7f94d92c...,...,"[222b67ff, 0f1923ff, 261e4fff, 0f192300]",ShooterGame/Content/Characters/Stealth/Stealth...,False,True,True,False,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,None,"[{'slot': 'Grenade', 'displayName': 'FAKEOUT',...",None
24,df1cb487-4902-002e-5c17-d28e83e78588,Waylay,Thailand's prismatic radiant Waylay transforms...,Terra,2025-03-04T22:00:00Z,None,https://media.valorant-api.com/agents/df1cb487...,https://media.valorant-api.com/agents/df1cb487...,https://media.valorant-api.com/agents/df1cb487...,https://media.valorant-api.com/agents/df1cb487...,...,"[482e61ff, 0f1923ff, 0f1923ff, 482e61ff]",ShooterGame/Content/Characters/Terra/Terra_Pri...,False,True,True,False,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,{'counterId': 'df1cb487-4902-002e-5c17-d28e83e...,"[{'slot': 'Ability2', 'displayName': 'Refract'...",None
25,569fdd95-4d10-43ab-ca70-79becc718b46,Sage,"The bastion of China, Sage creates safety for ...",Thorne,1970-01-01T00:00:00Z,"[Recovery, Stalling]",https://media.valorant-api.com/agents/569fdd95...,https://media.valorant-api.com/agents/569fdd95...,https://media.valorant-api.com/agents/569fdd95...,https://media.valorant-api.com/agents/569fdd95...,...,"[1f5148ff, 0f1923ff, 102d23ff, 0f192300]",ShooterGame/Content/Characters/Thorne/Thorne_P...,True,True,True,True,{'uuid': '5fc02f99-4091-4486-a531-98459a3e95e9...,None,"[{'slot': 'Ability1', 'displayName': 'Slow Orb...",None
26,a3bfb853-43b2-7238-a4f1-ad90e9e46bcc,Reyna,"Forged in the heart of Mexico, Reyna dominates...",Vampire,1970-01-01T00:00:00Z,"[Evasion, Self-Sustain]",https://media.valorant-api.com/agents/a3bfb853...,https://media.valorant-api.com/agents/a3bfb853...,https://media.valorant-api.com/agents/a3bfb853...,https://media.valorant-api.com/agents/a3bfb853...,...,"[662d62ff, 0f1923ff, 2f2664ff, 0f192300]",ShooterGame/Content/Characters/Vampire/Vampire...,False,True,True,False,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,None,"[{'slot': 'Ability1', 'displayName': 'Devour',...",None
27,8e253930-4c05-31dd-1b6c-968525494517,Omen,"A phantom of a memory, Omen hunts in the shado...",Wraith,1970-01-01T00:00:00Z,"[Mobility, Vision Control]",https://media.valorant-api.com/agents/8e253930...,https://media.valorant-api.com/agents/8e253930...,https://media.valorant-api.com/agents/8e253930...,https://media.valorant-api.com/agents/8e253930...,...,"[433178ff, 0f1923ff, 344673ff, 0f192300]",ShooterGame/Content/Characters/Wraith/Wraith_P...,False,True,True,False,{'uuid': '4ee40330-ecdd-4f2f-98a8-eb1243428373...,None,"[{'slot': 'Ability1', 'displayName': 'Paranoia...",None
28,add6443a-41bd-e414-f6ad-e58d267f4e95,Jett,"Representing her home country of South Korea, ...",Wushu,1970-01-01T00:00:00Z,"[Evasion, Mobility]",https://media.valorant-api.com/agents/add6443a...,https://media.valorant-api.com/agents/add6443a...,https://media.valorant-api.com/agents/add6443a...,https://media.valorant-api.com/agents/add6443a...,...,"[25607aff, 0f1923ff, 0f1923ff, 25607aff]",ShooterGame/Content/Characters/Wushu/Wushu_Pri...,False,True,True,True,{'uuid': 'dbe8757e-9e92-4ed4-b39f-9dfc589691d4...,None,"[{'slot': 'Ability1', 'displayName': 'Updraft'...",None

In [22]:
url = f'https://valorant-api.com/v1/competitivetiers'
response = requests.get(url)
lista_competitivo = response.json()
lista_competitivo
base_competitivo = pd.DataFrame(lista_competitivo['data'])
base_competitivo

,uuid,assetObjectName,tiers,assetPath
0,564d8e28-c226-3180-6285-e48a390db8b1,Episode1_CompetitiveTierDataTable,"[{'tier': 0, 'tierName': 'UNRANKED', 'division...",ShooterGame/Content/UI/Screens/Shared/Competit...
1,23eb970e-6408-bc0b-3f20-d8fb0e0354ea,Episode2_CompetitiveTierDataTable,"[{'tier': 0, 'tierName': 'UNRANKED', 'division...",ShooterGame/Content/UI/Screens/Shared/Competit...
2,edb72a72-7e6d-6010-9591-7c053bbdbf48,Episode3_CompetitiveTierDataTable,"[{'tier': 0, 'tierName': 'UNRANKED', 'division...",ShooterGame/Content/UI/Screens/Shared/Competit...
3,e4e9a692-288f-63ca-7835-16fbf6234fda,Episode4_CompetitiveTierDataTable,"[{'tier': 0, 'tierName': 'UNRANKED', 'division...",ShooterGame/Content/UI/Screens/Shared/Competit...
4,03621f52-342b-cf4e-4f86-9350a49c6d04,Episode5_CompetitiveTierDataTable,"[{'tier': 0, 'tierName': 'UNRANKED', 'division...",ShooterGame/Content/UI/Screens/Shared/Competit...